import { z } from "zod";
import { sourceSchema } from "@/features/catalog/contracts";
import { editSuggestionPatchSchema } from "@/features/catalog/edit-suggestions";
export const suggestionCopy = {
  en: {
    heading: "Suggest a correction",
    mine: "My edit suggestions",
    review: "Review edit suggestions",
    base: "Base work revision",
    current: "Current work revision",
    field: "Field to correct",
    value: "Proposed value",
    primaryTitle: "Primary title",
    primaryTitleLanguage: "Primary title language",
    releaseStatus: "Release status",
    publicationYear: "Publication year",
    publicationLabel: "Publication label",
    originalLanguage: "Original language",
    label: "Source label",
    citation: "Citation",
    url: "Public HTTPS source URL (optional)",
    submit: "Submit suggestion",
    busy: "Saving…",
    error: "Unable to save. Retry the same attempt or start a new one.",
    invalid:
      "Check the correction and citation limits: title 500, label 200, citation 4000 characters; year 1–9999; language code or public HTTPS URL.",
    stale:
      "The work or suggestion has changed. Reload to compare the latest revision; nothing was automatically resubmitted.",
    unavailable: "This work or suggestion is unavailable.",
    reload: "Reload latest revision",
    newAttempt: "Start a new attempt",
    pending:
      "An uncertain submission is frozen so retry sends exactly the same data.",
    denied:
      "Access denied. A verified account with the appropriate role is required.",
    back: "Back to work",
    empty: "No edit suggestions.",
    history: "Suggestion history",
    proposed: "Proposed metadata",
    currentMetadata: "Current metadata",
    identity: "Identity changes require explicit review; no automatic merge.",
    metadataAck: "I reviewed the metadata and identity changes",
    publicationAck: "I reviewed publication readiness",
    reason: "Review reason",
    approve: "Approve",
    reject: "Reject",
    saved: "Review saved",
    conflict:
      "Base and current revisions differ. Approval is unavailable; reject or reload.",
    previous: "Previous",
    next: "Next",
    page: "Page",
    state: "State",
    applied: "Applied work revision",
    reasonSaved: "Review reason",
    submitted: "Submitted",
    approved: "Approved",
    rejected: "Rejected",
    missing: "Not available",
    settings: "Account settings",
  },
  vi: {
    heading: "Đề xuất chỉnh sửa",
    mine: "Đề xuất chỉnh sửa của tôi",
    review: "Duyệt đề xuất chỉnh sửa",
    base: "Phiên bản tác phẩm gốc",
    current: "Phiên bản tác phẩm hiện tại",
    field: "Trường cần chỉnh sửa",
    value: "Giá trị đề xuất",
    primaryTitle: "Tên chính",
    primaryTitleLanguage: "Ngôn ngữ tên chính",
    releaseStatus: "Tình trạng phát hành",
    publicationYear: "Năm xuất bản",
    publicationLabel: "Nhãn xuất bản",
    originalLanguage: "Ngôn ngữ gốc",
    label: "Nhãn nguồn",
    citation: "Trích dẫn",
    url: "URL nguồn HTTPS công khai (không bắt buộc)",
    submit: "Gửi đề xuất",
    busy: "Đang lưu…",
    error: "Không thể lưu. Thử lại cùng lần gửi hoặc bắt đầu lần mới.",
    invalid:
      "Kiểm tra giới hạn chỉnh sửa và trích dẫn: tên 500, nhãn 200, trích dẫn 4000 ký tự; năm 1–9999; mã ngôn ngữ hoặc URL HTTPS công khai.",
    stale:
      "Tác phẩm hoặc đề xuất đã thay đổi. Tải lại để so sánh phiên bản mới nhất; không tự động gửi lại.",
    unavailable: "Tác phẩm hoặc đề xuất không khả dụng.",
    reload: "Tải lại phiên bản mới nhất",
    newAttempt: "Bắt đầu lần gửi mới",
    pending:
      "Lần gửi chưa xác định được giữ nguyên để thử lại với đúng dữ liệu cũ.",
    denied:
      "Không có quyền truy cập. Cần tài khoản đã xác minh với vai trò phù hợp.",
    back: "Trở lại tác phẩm",
    empty: "Chưa có đề xuất chỉnh sửa.",
    history: "Lịch sử đề xuất",
    proposed: "Thông tin đề xuất",
    currentMetadata: "Thông tin hiện tại",
    identity:
      "Thay đổi danh tính cần xét duyệt rõ ràng; không tự động hợp nhất.",
    metadataAck: "Tôi đã xem xét thông tin và thay đổi danh tính",
    publicationAck: "Tôi đã xem xét khả năng công bố",
    reason: "Lý do xét duyệt",
    approve: "Chấp thuận",
    reject: "Từ chối",
    saved: "Đã lưu xét duyệt",
    conflict:
      "Phiên bản gốc và hiện tại khác nhau. Không thể chấp thuận; hãy từ chối hoặc tải lại.",
    previous: "Trước",
    next: "Tiếp",
    page: "Trang",
    state: "Trạng thái",
    applied: "Phiên bản tác phẩm đã áp dụng",
    reasonSaved: "Lý do xét duyệt",
    submitted: "Đã gửi",
    approved: "Đã chấp thuận",
    rejected: "Đã từ chối",
    missing: "Không có",
    settings: "Cài đặt tài khoản",
  },
};
export const suggestionReplySchema = z
  .object({
    id: z.uuid(),
    workId: z.uuid(),
    baseWorkRevision: z.number().int().positive(),
    revision: z.number().int().positive(),
    state: z.enum(["SUBMITTED", "APPROVED", "REJECTED"]),
    patch: editSuggestionPatchSchema,
    citation: sourceSchema,
    reviewReason: z.string().nullable(),
    appliedWorkRevision: z.number().int().positive().nullable(),
    createdAt: z.string().datetime({ offset: true }),
    updatedAt: z.string().datetime({ offset: true }),
  })
  .strict();
export type SuggestionView = z.infer<typeof suggestionReplySchema>;
